Algoritmo "Exercício 09"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/10/2021
Var
// Seção de Declarações das variáveis 
R, D: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite a quantidade de dinheiro em sua carteira: R$")
Leia(R)
D <- (R/5.46)
Escreva("Você poderá comprar: U$",D:5:2,".")

Fimalgoritmo