Algoritmo "Exercício 06"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2021
Var
// Seção de Declarações das variáveis
N, Nant, Nsuc: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite um número: ")
Leia(N)
Nant <- (N-1)
Nsuc <- (N+1)
Escreval("O antecessor de ",N," é",Nant,".")
Escreva("O sucessor de ",N," é",Nsuc,".")

Fimalgoritmo