Algoritmo "Exercício 03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2021
Var
// Seção de Declarações das variáveis 
Nome: Caractere
Salario: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Nome do funcionário: ")
Leia(Nome)
Escreva("Salário R$")
Leia(Salario)
Escreva("O funcionário ", Nome," têm um salário de R$", Salario," no mês de Junho.")
Fimalgoritmo