Algoritmo "Exercício 39"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/10/2021
Var
// Seção de Declarações das variáveis 
Contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Contador <- 10
Enquanto (Contador >=3) faca
          Escreva(Contador)
          Contador <- (Contador - 1)
Fimenquanto
Escreva(" Acabou!")
Fimalgoritmo