Algoritmo "Exercício 71"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/11/2021
Var
// Seção de Declarações das variáveis 
V: Vetor[0..7] de inteiro
C, N: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   N <- Randi(999)

   Para C <- 0 Até 7 Faca
        V[C] <- N
        Escreva(V[C]:3," ")
   Fimpara
   Escreval("")

Fimalgoritmo