Algoritmo "Exercício 20"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2021
Var
// Seção de Declarações das variáveis 
N: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Informe um número inteiro: ")
Leia(N)
Se (N % 2 = 0) entao
    Escreval("O número",N," é par.")
Senao
    Escreval("O número",N," é ímpar.")
Fimse

Fimalgoritmo