Algoritmo "Exercício 61"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/11/2021
Var
// Seção de Declarações das variáveis 
Contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Contador <- 0
Enquanto (Contador <= 30) Faça
          Escreva(Contador)
          Contador <- Contador + 3
Fimenquanto
Escreva(" Acabou!")
Fimalgoritmo