Algoritmo "Exercício 86"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2021
Var
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Procedimento Gerador()
Inicio
   Escreval("+-------=======------+")
   Escreval("      Olá, Mundo!     ")
   Escreval("+-------=======------+")
Fimprocedimento

Gerador()

Fimalgoritmo