Algoritmo "Exercício 04"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2021
Var
// Seção de Declarações das variáveis 
N1, N2, Soma: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite um valor: ")
Leia(N1)
Escreva("Digite um outro valor: ")
Leia(N2)
Soma <- (N1 + N2)
Escreva("A soma entre ",N1," e",N2," é igual a",Soma,".")

Fimalgoritmo