Algoritmo "Exercício 13"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/10/2021
Var
// Seção de Declarações das variáveis 
S, NS: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Valor do salário do funcionário: R$")
Leia(S)
NS <- (S + (S*0.15))
Escreva("O novo salário do funcionário é: R$", NS:5:2,".")

Fimalgoritmo