Algoritmo "Exercício 02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2021
Var
// Seção de Declarações das variáveis 
Nome: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Qual o seu nome? ")
Leia(Nome)
Escreva("Olá ", Nome, ", é um prazer te conhecer!")

Fimalgoritmo