Algoritmo "Exercício 05"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2021
Var
// Seção de Declarações das variáveis 
N1, N2, M: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Escreva a nota 1: ")
Leia(N1)
Escreva("Escreva a nota 2: ")
Leia(N2)
M <- (N1 + N2)/2
Escreva("A média entre ",N1, " e",N2," é igual a",M,".")
Fimalgoritmo