Algoritmo "Exercício 12"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/10/2021
Var
// Seção de Declarações das variáveis 
V, VD: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Valor do produto R$")
Leia(V)
VD <- (V-(V*0.05))
Escreva("O valor do produto com desconto é: R$", VD:5:2,".")

Fimalgoritmo