Algoritmo "Exercício 67"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/11/2021
Var
// Seção de Declarações das variáveis 
N, C: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Informe um número: ")
Leia(N)
Escreval("")
Para C <- 0 Até N Passo 1 Faça
     Escreva(C,",")
Fimpara
Escreva(" FIM!")
Escreval("")
Fimalgoritmo