Algoritmo "Exercício 21"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2021
Var
// Seção de Declarações das variáveis 
A: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Informe o ano: ")
Leia(A)
Se(A % 4 = 0)entao
   Escreva("O ano ",A," é bissexto.")
Senao
   Escreva("O ano ",A," não é bissexto.")
Fimse

Fimalgoritmo