Algoritmo "Exercício 56"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/11/2021
Var
// Seção de Declarações das variáveis 
Somador, N: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Somador <- 0
Repita
    Escreva("Informe um número: ")
    Leia(N)
    Somador <- Somador + N
Até(N = 1111)
Escreva("A soma total dos números idicados é",Somador,".")
Fimalgoritmo