Algoritmo "Exercício 07"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2021
Var
// Seção de Declarações das variáveis 
N, Dobro, Tercaparte: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite um número: ")
Leia(N)
Dobro <- (2*N)
Tercaparte <- (N/3)
Escreval("O dobro de ", N," é", Dobro,".")
Escreva("A terça parte de ", N," é", Tercaparte,".")

Fimalgoritmo